### ISSUE TITLE
Error downloading org.jetbrains.kotlinx:kotlinx-html-jvm:0.7.2

### ISSUE THREAD

**Issue by fletchgqc** [dustinsand/pre-commit-jvm#2]
I just set it up and I get this error: 

`   Downloading https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.2/kotlinx-html-jvm-0.7.2.pom.sha1
    Downloaded https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.2/kotlinx-html-jvm-0.7.2.pom.sha1
    Exception in thread "main" coursier.error.ResolutionError$CantDownloadModule: Error downloading org.jetbrains.kotlinx:kotlinx-html-jvm:0.7.2
      not found: https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.2/kotlinx-html-jvm-0.7.2.pom
      forbidden: https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlinx/kotlinx-html-jvm/0.7.2/kotlinx-html-jvm-0.7.2.pom
        at coursier.Resolve$.$anonfun$validate$1(Resolve.scala:323)
`

**Comment by dustinsand** [comment]
It looks like a repository change with bintray I will need to resolve.  Apologies, but the earliest I will be able to fix this is by this weekend.

**Comment by dustinsand** [comment]
It looks like a repository change with bintray I will need to resolve.  Apologies, but the earliest I will be able to fix this is by this weekend.

**Comment by chrismgrayftsinc** [comment]
I am also seeing this problem FWIW.  I don't have a private artifact repository.  I am only using the `google-java-formatter-jdk11` hook.

**Comment by dustinsand** [comment]
Thank you to @chrismgrayftsinc for the PR to fix this issue.  v0.3.0 will resolve your issue @fletchgqc.
