### ISSUE TITLE
google-java-format doesn't work on Java 16+

### ISSUE THREAD

**Issue by chrismgrayftsinc** [dustinsand/pre-commit-jvm#6]
See https://github.com/google/google-java-format#jdk-16

**Comment by dustinsand** [comment]
I was unable to find the correct syntax for Coursier to fix this issue so I opened a question on [Stackoverflow](https://stackoverflow.com/questions/70550186/how-do-i-pass-java-command-line-options-to-coursier-when-the-java-option-is-two).

**Comment by dustinsand** [comment]
Fixed in #8
